// <auto-generated />
namespace CarDatingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class meginajums7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(meginajums7));
        
        string IMigrationMetadata.Id
        {
            get { return "201801061917573_meginajums7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
